import React from 'react';
import Head from "next/head";

function Guides(props) {
    return (
        <div>
            <Head>
                <title>Next_N_|Guide</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Guides</h1>
        </div>
    );
}

export default Guides;